### PR TITLE
fixed offline usage with multiple users

### LINKED ISSUE #102: Allow more than one offline-user
The CP should allow more than one offline-users.

The PAM module does this by storing the credentials in a local database with the columns `username` and `serial`. This way we can handle several offline users and also offline users with different tokens.

### PR DESCRIPTION
**Pull request by nilsbehlen**
offline data of a new user was not recognized as "new" and therefore not added, closes #102

### CODE REVIEW

File: CppClientCore/CppClientCore/OfflineHandler.cpp [hunk 1]
```diff
@@ -50,13 +50,17 @@ OfflineHandler::OfflineHandler(const wstring& filePath, int tryWindow)
 	_filePath = filePath.empty() ? _filePath : filePath;
 	_tryWindow = tryWindow == 0 ? _tryWindow : tryWindow;
 	const HRESULT res = LoadFromFile();
-	if (res != S_OK)
+	if (res == S_OK)
 	{
-		DebugPrint(L"Unable to load offline file: " + to_wstring(res) + L": " + getErrorText(res));
+		DebugPrint("Offline data loaded successfully!");
+	}
+	else if (res == 2)
```
Comment (plettich) [inline CppClientCore/CppClientCore/OfflineHandler.cpp:57]: shouldn't that be some kind of constant?

**Review by plettich — COMMENTED** [review]
Looks good, just a small question

File: CppClientCore/CppClientCore/OfflineHandler.cpp (hunk 1 above)
Comment (nilsbehlen) [reply CppClientCore/CppClientCore/OfflineHandler.cpp:57]: you're right, ill replace it with the macro name
