### PR TITLE
improved logging, fixes, version 3.1.2

### LINKED ISSUE #76: Enable debug log from registry instead of macro

### LINKED ISSUE #83: Add possibility to reset login
in case of two-step, there needs to be a way to reset the login.
This could be done using the hyperlink.

### LINKED ISSUE #84: Utilities::ResetScenario throws nullptr exception
Resetting the scenario crashes the CP. The scenario is reset in case of deselecting the tile.
`_config->_pCredProvCredentialEvents` is a nullptr there.

### LINKED ISSUE #85: Write all registry entries on installation
Let the installer insert all possible config entry in the registry, eventhough they are not directly configurable in the installer.
This will prevent misunderstandings / wrong spelling.

### LINKED ISSUE #88: German translation has a typo
"Bitte geben Sie ihren zweiten Faktor ein!"
please write "ihren" with a capital Letter "Ihren".
->
"Bitte geben Sie Ihren zweiten Faktor ein!"

### LINKED ISSUE #89: no_default setting is not loaded
it is used (always default value) but not loaded from the config.

### PR DESCRIPTION
**Pull request by nilsbehlen**
* Added WinHttpStatusCallback to get more information about secure failure cases (#82)
* Removed the need to install the debug version for detailed debug output. Instead, this controlled via registry entry (closes #76)
* Fixed typo in german translation (closes #88)
* Added optional command link to reset the login (closes #83)
* Fixed nullptr when deselecting the CP (closes #84)
* Fixed missing load of no_default config entry (closes #89)
* Removed SecureString because of compiler problems
* Change method names to adhere to convention (starting with capital letters)
* Installer writes all possible keys to registry (closes #85)

### CODE REVIEW

File: CppClientCore/CppClientCore/Logger.cpp [hunk 1]
```diff
@@ -27,20 +26,13 @@
...
 {
-#ifdef _DEBUG
-	UNREFERENCED_PARAMETER(logInProduction);
-#endif
-	// Check if it should be logged first and to which file
-	string outfilePath = logfilePathDebug;
-#ifndef _DEBUG
-	if (!logInProduction || !this->releaseLog)
+	// Do not log debug messages if it is not enabled
+	if (!logDebug && isDebugMessage)
```
Comment (cornelinux) [inline CppClientCore/CppClientCore/Logger.cpp:32]: Is `logDebug` defined at all?

File: CredentialProvider/Configuration.cpp [hunk 2]
```diff
@@ -25,65 +25,66 @@
...
 using namespace std;
 
-const wstring Configuration::registryPath = L"SOFTWARE\\Netknights GmbH\\PrivacyIDEA-CP\\";
-const wstring Configuration::registryRealmPath = L"SOFTWARE\\Netknights GmbH\\PrivacyIDEA-CP\\realm-mapping";
-
-Configuration::Configuration()
+void Configuration::Load()
 {
-	RegistryReader rr(registryPath);
+	RegistryReader rr(L"SOFTWARE\\Netknights GmbH\\PrivacyIDEA-CP\\");
```
Comment (cornelinux) [inline CredentialProvider/Configuration.cpp:30]: Having the registry path in a constant looks sensible to me.
Why remove it and put it directly in the code?

**Review by cornelinux — COMMENTED** [review]
Please note my comments.

File: CppClientCore/CppClientCore/Logger.cpp (hunk 1 above)
Comment (nilsbehlen) [reply CppClientCore/CppClientCore/Logger.cpp:32]: it is defined in the header and overwritten in the ctor of the Provider, directly after loading the configuration.

File: CredentialProvider/Configuration.cpp (hunk 2 above)
Comment (nilsbehlen) [reply CredentialProvider/Configuration.cpp:30]: Because it is not used anywhere else and was defined in Configuration.h. I guess it makes sense to gather all registry paths in the header of RegistryReader

File: CppClientCore/CppClientCore/Logger.cpp (hunk 1 above)
Comment (cornelinux) [reply CppClientCore/CppClientCore/Logger.cpp:32]: Thanks

File: CredentialProvider/Configuration.cpp (hunk 2 above)
Comment (cornelinux) [reply CredentialProvider/Configuration.cpp:30]: Do you want to do this, now? Or later?

Comment (nilsbehlen) [reply CredentialProvider/Configuration.cpp]: did it just now, its only 3 things ;)
